# Generated by Django 3.1.6 on 2021-02-10 04:51

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('piggybox', '0002_auto_20210210_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(default=datetime.time(7, 0), verbose_name='終了時間'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='in_out',
            field=models.IntegerField(default=1, verbose_name='収支'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(default=datetime.time(7, 0), verbose_name='開始時間'),
        ),
    ]
