# Generated by Django 3.1.6 on 2021-02-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggybox', '0009_auto_20210210_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='category',
            field=models.CharField(choices=[('poc', 'おこずかい'), ('sal', '給与'), ('oti', 'その他所得'), ('foo', '食費'), ('boo', '教育'), ('tra', '交通費'), ('sho', 'ショッピング'), ('prs', 'プレゼント'), ('ent', '交際費'), ('fee', '手数料'), ('oto', 'その他消費')], default='foo', max_length=3, verbose_name='カテゴリー'),
        ),
    ]
