# Generated by Django 3.1.6 on 2021-02-10 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggybox', '0010_auto_20210210_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='画像')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999)], verbose_name='価格')),
                ('target_date', models.DateTimeField(verbose_name='達成予定日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
            ],
        ),
        migrations.AlterField(
            model_name='schedule',
            name='summary',
            field=models.CharField(blank=True, max_length=50, verbose_name='詳細'),
        ),
    ]
