# Generated by Django 3.1.6 on 2021-02-11 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('piggybox', '0011_auto_20210211_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='wisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='target_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='達成予定日'),
        ),
    ]
