# Generated by Django 3.1.6 on 2021-02-11 05:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('piggybox', '0012_auto_20210211_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日付')),
                ('in_out', models.IntegerField(validators=[django.core.validators.MinValueValidator(-999999), django.core.validators.MaxValueValidator(999999)], verbose_name='収支')),
                ('category', models.CharField(choices=[('poc', 'おこずかい'), ('sal', '給与'), ('oti', 'その他所得'), ('foo', '食費'), ('boo', '教育'), ('tra', '交通費'), ('sho', 'ショッピング'), ('prs', 'プレゼント'), ('ent', '交際費'), ('fee', '手数料'), ('oto', 'その他消費')], default='foo', max_length=3, verbose_name='カテゴリー')),
                ('summary', models.CharField(blank=True, max_length=50, verbose_name='内容')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='wisher',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
